version: '3'

services:
  db:
    image: postgres:11
    volumes:
      - postgres_volume:/var/lib/postgresql
    env_file:
      - local.env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - local.env
volumes:
  postgres_volume:
